language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gakalmar/fibonacci-calculator-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gakalmar/fibonacci-calculator-test npm run test

after_success:
  - docker build -t gakalmar/fibonacci-calculator-client -f ./client/Dockerfile ./client
  - docker build -t gakalmar/fibonacci-calculator-worker -f ./worker/Dockerfile ./worker
  - docker build -t gakalmar/fibonacci-calculator-server -f ./server/Dockerfile ./server
  - docker build -t gakalmar/fibonacci-calculator-nginx -f ./nginx/Dockerfile ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push gakalmar/fibonacci-calculator-client
  - docker push gakalmar/fibonacci-calculator-worker
  - docker push gakalmar/fibonacci-calculator-server
  - docker push gakalmar/fibonacci-calculator-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: fibonacci-calculator
  env: Fibonacci-calculator-env
  bucket_name: elasticbeanstalk-eu-west-2-891376988072
  bucket_path: fibonacci-calculator
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY